### ISSUE TITLE
Add line chart for average NDVI/NDWI 

### ISSUE THREAD

**Issue by alexkiro** [ogorlab/ogor-frontend#266]
Some details:

 - only include observations that have 0% cloud coverage 
 - only include observations that have an average of over 0.25
 - use rounded line chart

**Comment by ppscvalentin** [comment]
Great job!

**Comment by ppscvalentin** [comment]
![image](https://user-images.githubusercontent.com/4716271/91415190-5a6ac680-e856-11ea-9078-41e891281bff.png)

http://staging.ogor.edw.ro/map/nY0d1zm/season/d7pa60B/date/2019-07-25/parcel/7pxkD9e/details?zoom=15&center=46.9425215,28.0294543

I am on 25 Jul 2019, Silvia's farm and the current NDVI is not highlighted on the chart (with vertical line and dot). The highlight shows when hovering on across the chart, but when I get to 25 Jul it dissapears.

If I navigate by two observations in the future the highlight appears as expected, so the bug is kind of random.

**Comment by alexkiro** [comment]
> If I navigate by two observations in the future the highlight appears as expected, so the bug is kind of random.

Hmm, damn, we failed to account for the observations we are excluding because of cloud coverage.

**Comment by alexkiro** [comment]
> Hmm, damn, we failed to account for the observations we are excluding because of cloud coverage.

We ended up including the observations with cloud coverage as well, works as expected now.
